### ISSUE TITLE
Question: Should runtime metrics match dropsonde?

### ISSUE THREAD

**Issue by jmcarp** [cloudfoundry/go-loggregator#30]
Some of the runtime metrics emitted by `dropsonde` aren't emitted here, like `memoryStats.numMallocs`, `memoryStats.numFrees`, and `numCPUS`. Should metrics match between `dropsonde` and this package, or were those metrics not useful enough to include here?

**Comment by apoydence** [comment]
Its been a while since the decision was made, but I believe we worked with a  few other teams (e.g., diego) to decide which metrics were being used. This was then reflected in the [RuntimeEmitter](https://github.com/cloudfoundry/go-loggregator/blob/f94bd5dfaf4567c35b26d90894d2b07b450100a9/runtimeemitter/runtime_emitter.go).

**Comment by jmcarp** [comment]
Thanks @apoydence ! Does that mean the legacy metrics from `dropsonde` will eventually be dropped as CF components switch over to `go-loggregator`? Is `dropsonde` deprecated?

**Comment by apoydence** [comment]
@jmcarp This is correct. If you depend on these metrics, please add an issue so we can consider adding it to the RuntimeEmitter.
